style = {
    'Déclarations Prophétiques' : 'Utilisation de phrases déclaratives pour affirmer des vérités spirituelles (e.g., "Je déclare et je décrète...").',
    'Exhortations' : 'Appels directs à l\’action et à la réflexion (e.g., "Reçois cette onction", "Cherche ton enfant...").',
    'Narratif' : 'Utilisation de récits bibliques et contemporains pour illustrer des points (e.g., histoire de Joseph et Marie).',
    'Encouragement' : 'Encouragement des auditeurs à persévérer dans leur foi et leur marche spirituelle (e.g., "Garde ta virginité si tu l\’es encore...").',
    'Didactique' : 'Explication des concepts théologiques et spirituels de manière claire et détaillée (e.g., distinction entre justice et miséricorde).',
    'Interrogatif' : 'Pose de questions pour engager l\’audience et susciter la réflexion personnelle (e.g., "Que fais-tu quand ton mari... ?").',
    'Appel à la Réflexion' : 'Invitation à examiner sa propre vie et ses actions à la lumière des enseignements (e.g., "Quel est l\’état de ta relation avec ton père ou ta mère ?").',
    'Langage Imagé' : 'Utilisation de métaphores et d’images puissantes pour illustrer des concepts spirituels (e.g., "marche sur les eaux").',
    'Pragmatique' : 'Conseils pratiques pour la vie quotidienne et spirituelle (e.g., "Choisissez bien vos amis").',
    'Comparatif' : 'Comparaison entre différents états spirituels ou comportements (e.g., vierges sages vs vierges folles).',
    'Analogie' : 'Utilisation d’analogies pour clarifier des concepts (e.g., l\’huile symbolisant l\’onction).',
    'Citation Biblique' : 'Utilisation fréquente de versets bibliques pour soutenir les points avancés.',
    'Répétition' : 'Répétition de mots-clés et de phrases pour renforcer le message (e.g., "désir", "onction").',
    'Contraste' : 'Mise en contraste de comportements opposés pour souligner des enseignements (e.g., miséricorde vs justice).',
    'Appel à l\’Action' : 'Instructions claires pour passer à l\’action après l\’écoute du sermon (e.g., "Va vers l\’autre et fais de ton mieux pour arranger la situation").',
    'Déclarations de Bénédiction' : 'Bénédictions prononcées sur l\’audience pour clôturer le message (e.g., "Je déclare et je décrète la restauration de toutes les relations familiales...").',
    'Proclamations de Foi' : 'Proclamations encourageant la foi et la confiance en Dieu (e.g., "Reçois l\’onction pour discerner les songes").',
    'Apel à la Prière' : 'Invitation à prier et à chercher Dieu pour obtenir des réponses et des solutions (e.g., "Prie que le Seigneur t’accorde la sagesse").',
    'Anecdotes Personnelles' : 'Récits personnels pour illustrer des points et rendre le message plus relatable (e.g., histoires de vie de pasteurs ou de membres de l\’audience).',
    'Instructions Spécifiques' : 'Instructions précises sur des actions à entreprendre (e.g., "Ne laisse pas Satan détruire votre mariage").',
}